### ISSUE TITLE
Dockless Data: Rename Page Title and Move About Text

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/transportation-datahub#235]
1. Rename "Dockless Mobility Summary Counts" to "Dockless Mobility Overview" to be consistent with operations overview.

2. The text at the top of the dockless data looks a bit out of place. Let's move it to the bottom of the page, under an "About" header. This is more or less consistent with the other pages on the site.

This is the text I'm referring to:
<img width="940" alt="screen shot 2018-12-21 at 2 35 41 pm" src="https://user-images.githubusercontent.com/14793120/50362548-c51a1980-052d-11e9-9463-7341324757b1.png">

**Comment by amenity** [comment]
Lol, was just about to add an issue to update the title to "Dockless Reporting Dashboard" or just "Dockless Dashboard" like the link in the Medium post. 
 ![Screen Shot 2019-06-27 at 2 39 25 PM](https://user-images.githubusercontent.com/1463708/60295484-6c1aac00-98e9-11e9-9e40-d952dc513652.png)

🙃

**Comment by mateoclarke** [comment]
@amenity we're actually about to rename it to Micromobility Dashboard. 🙃

**Comment by amenity** [comment]
🙌
