### ISSUE TITLE
Dockless Mobility: Default selected month to current month

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/transportation-datahub#251]
Current the dockless dashboard shows February data, but we're in March. The app should default to displaying the current month's data.

**Comment by mateoclarke** [comment]
I did that on purpose because the current month doesn't always have complete data (esp at the beginning of the month). Easy change if you want me to do this @johnclary...

**Comment by johnclary** [comment]
Cool. Thought that might be the case. After spending more time using the dashboard this month, and having a public user get confused by it, I'm in favor defaulting to current month-to-date totals.

**Comment by mateoclarke** [comment]
This should've been closed with #252
